import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

// esbuild bundles src/main.ts -> main.js (the file Obsidian loads).
//   node esbuild.config.mjs              -> watch mode (dev)
//   node esbuild.config.mjs production   -> one-shot minified build

const production = process.argv[2] === "production";

const banner = `/*
This file is auto-generated by esbuild from the TypeScript sources in src/.
Do not edit it directly — edit src/ and rebuild. See docs/CONTRIBUTING.md.
*/`;

const context = await esbuild.context({
  entryPoints: ["src/main.ts"],
  bundle: true,
  // Obsidian, Electron, and Node builtins are provided by the host at runtime.
  external: ["obsidian", "electron", ...builtinModules],
  format: "cjs",
  target: "es2018",
  platform: "browser",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  minify: production,
  treeShaking: true,
  outfile: "main.js",
  banner: { js: banner },
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
